### ISSUE TITLE
Section 7.7 - CHOOSE in all caps

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#11]
Not sure it should be:

   If classification is preformed before BIMI is evaluated then a
   receiver MAY CHOOSE to skip BIMI processing for that message, in this
   case they SHOULD add a bimi=skipped entry to the Authentication-
   Results header for that message, and SHOULD add a comment stating the
   reasons for skipping BIMI processing.

I know "MAY" should be, but perhaps the phrase should be written as "MAY choose"

**Comment by marcbradshaw** [comment]
sure
