### ISSUE TITLE
SPF/DKIM/DMARC requirement doesn't provide meaningful authentication without DNSSEC

### ISSUE THREAD

**Issue by thestinger** [authindicators/BIMI_Receiver_Guidance#18]
It should be required that DNSSEC is implemented and verified by the receiver for the full set of DNS records required for SPF/DKIM/DMARC. If that's not provided, these standards aren't actually authenticating the domain. The current requirements are vulnerable to spoofing and don't provide the expected authenticity guarantees implied, which can be considered a vulnerability in the specification.

**Comment by marcbradshaw** [comment]
@thestinger, would you please start a discussion about this on the [IETF BIMI mailing list](https://www.ietf.org/mailman/listinfo/bimi)

Thanks.

**Comment by abrotman** [comment]
Moving this to the IETF list.  @thestinger You're invited, bimi@ietf.org  https://www.ietf.org/mailman/listinfo/bimi
