### ISSUE TITLE
Section 3 - strike past three decades

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#2]
It is possible that this document will endure for a number of years, and so therefore the first sentence of the second paragraph in this section unnecessarily dates the document:

   As email has evolved over the past three decades, it is no longer a
   medium of merely exchanging text, but of enabling people to build
   rich experiences on top of it.

I would just remove "over the past three decades" from this sentence.

**Comment by marcbradshaw** [comment]
removed
