### ISSUE TITLE
Section 6.1  BIMI Site Requirements

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#4]
The title of this section gives me the expectation that this will help me understand what capabilities a receiver must have in order to implement BIMI. The text does not meet my expectation.

This section is a discussion of hypothetical extra requirements that a receiving site my impose on a sender in order to get their logo shown. That's perfectly fine, but again for me it doesn't match with the section title.

Perhaps the section title can be "Additional Considerations or Suggestions for Implementing BIMI" or some such.

**Comment by marcbradshaw** [comment]
sure
