### ISSUE TITLE
Section 7 - No one bullet list

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#6]
current text starts with:

   In order for a receiver that has implemented BIMI to notify an MUA
   that it should display the images:

   o  An MTA must verify BIMI, and if it passes, add additional headers
      containing the logo to be displayed.

My high school English teacher drilled into my skull that lists should always have at least two items. This bullet is not necessary; suggested rewrite:

   In order for a receiver that has implemented BIMI to notify an MUA
   that it should display the images, an MTA must verify BIMI, and if it passes, 
   add additional headers containing the logo to be displayed.

**Comment by marcbradshaw** [comment]
Maybe there used to be more points here, but yes let's:

 * not have any one bullet lists
