### ISSUE TITLE
Section 7.5 - Is this a valid concern?

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#8]
Tracking pixels have been a thing in email for forever, so I'm not sure that BIMI introduces much new in the way of possible privacy exposure.

Perhaps MUAs configured to not display images by default can also not display brand indicators by default?

**Comment by marcbradshaw** [comment]
The concern isn't new with BIMI, and it's well understood. I think it's still a concern so should be mentioned here.
