### ISSUE TITLE
Section 7.6 - Requiring receivers to honor DMARC policies?

### ISSUE THREAD

**Issue by toddherr** [authindicators/BIMI_Receiver_Guidance#9]
First bulleted paragraph:

   o  Upon receipt of a message, the receiver checks to see if the
      message passes aligned-SPF or DKIM, and DMARC, and ensures that
      the sending domain has a DMARC policy of "quarantine" or "reject"
      per local receiver policy, **while properly applying the appropriate
      DMARC policy to the message.**

That last clause reads to my like it might be requiring or at least asking that a receiver accept a message solely because it passes DMARC, and we know that messages that pass DMARC get rejected all the time for valid reasons that have nothing to do with DMARC.

**Comment by marcbradshaw** [comment]
I'll improve the section to make this clearer.
